### ISSUE TITLE
Create pipeline to run Heart bit test for Cloud SDK

### ISSUE THREAD

**Issue by dpatel7** [filetrust/cdr-plugin-f2f-automation-tests#7]
require to run some constant running test which simply send a file at a time to Cloud SDK to make sure is up and running and is processing the file as expected.

Need to know Endpoint
What Testing we want to do.

**Comment by rajmbcoderx** [comment]
@dpatel7 I have shared this collection in the chat. Do you want to me to create a github workflow to run the collection?
